---
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
install:
  # development/testing dependencies
  - pip install -r requirements.txt
  - pip install --editable .
# run tests
script: nosetests
